#!/usr/bin/env php
<?php

/**
 * This file is part of the Twig Gettext utility.
 *
 *  (c) Саша Стаменковић <umpirsky@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Extracts translations from twig templates.
 *
 * @author Саша Стаменковић <umpirsky@gmail.com>
 */

// Init composer
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

// Init twig + core extensions
$twig = new Twig_Environment(new Twig\Gettext\Loader\Filesystem(DIRECTORY_SEPARATOR), array(
    'cache'       => implode(DIRECTORY_SEPARATOR, array(sys_get_temp_dir(), 'cache', uniqid()) ),
    'auto_reload' => true
));

$twig->addExtension(new Twig_Extensions_Extension_I18n());

// Read argv for config
array_shift($_SERVER['argv']);

$argvReadingTemplates = false;
$argvReadingFilters = false;

$resetArgv = function () use (&$argvReadingFilters, &$argvReadingTemplates) {
    $argvReadingFilters = false;
    $argvReadingTemplates = false;
};

$extractor = new Twig\Gettext\Extractor($twig);

/**
 * Syntax for argv:
 * 
 * twig-gettext-extractor <xgettext arguments> <extractor arguments>
 * 
 * xgettext arguments can be "--sort-output", "--force-po", etc and are processed directly.
 * extractor arguments are specific to the twig extractor
 * 
 * --files          Add a template file to the list of files that need to be extracted.
 * --filters        Add a dummy filter that is custom to the project to prevent the extractor breaking.
 */

foreach ($_SERVER['argv'] as $argument) {
    // Command starters ------------------------------------------------------------------------------------------------
    if ($argument === '--filters') {
        $resetArgv();
        $argvReadingFilters = true;
        continue;
    }
    
    if ($argument === '--files') {
        $resetArgv();
        $argvReadingTemplates = true;
        continue;
    }
    
    // Command parameters ----------------------------------------------------------------------------------------------
    if ($argvReadingFilters) {
        // We are in a --filters statement
        $twig->addFilter(new Twig_SimpleFilter($argument, function ($input) { return $input; }));
    } else if ($argvReadingTemplates) {
        // We are in a --files statement
        $extractor->addTemplate(getcwd() . DIRECTORY_SEPARATOR . $argument);
    } else {
        // We are not in a statement, process as gettext parameter
        $extractor->addGettextParameter($argument); 
    }
}

$extractor->extract();
