#!/usr/bin/env php
<?php

/**
 * This file is part of the Twig Gettext utility.
 *
 *  (c) Саша Стаменковић <umpirsky@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Twig\Gettext\Util\DebugLogger;

if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

try {
    $twig = new Twig_Environment(new Twig\Gettext\Loader\Filesystem(DIRECTORY_SEPARATOR), array(
        'cache' => implode(DIRECTORY_SEPARATOR, array(sys_get_temp_dir(), 'cache', uniqid())),
        'auto_reload' => true
    ));

    $twig->addExtension(new Twig_Extensions_Extension_I18n());

    array_shift($_SERVER['argv']);
    $addTemplate = false;

    $extractor = new Twig\Gettext\Extractor($twig);

    foreach ($_SERVER['argv'] as $arg) {
        if ('--files' == $arg) {
            $addTemplate = true;
        } else if ($addTemplate) {
            $extractor->addTemplate(getcwd() . DIRECTORY_SEPARATOR . $arg);
        } else {
            $extractor->addGettextParameter($arg);
        }
    }

    $extractor->extract();
} catch (Exception $ex) {
    DebugLogger::log("A Twig gettext extractor run has failed with an exception.");
    DebugLogger::log("Command: " . print_r($argv, true));
    DebugLogger::log("Exception: " . print_r($ex, true));

    exit(-1); // Die with a non zero exit code so poedit knows we failed
}